library(readxl)
library(tidyverse)
q6 <- read_excel("D:/Users/Eduardo/Downloads/conta_telef_depto.xlsx")
q6$`VALOR LIGACAO` <- round(q6$`VALOR LIGACAO`, 2)
q7 <- cbind(q6, MEDIA = with(q6, ave(q6$`VALOR LIGACAO`, q6$UF, FUN = mean)))
q6 <- round(q6$`VALOR LIGACAO`, 2)
resp <- data.frame(UF = q7$UF, `VALOR TELEFONICO MEDIA` = q7$MEDIA)
resp <- resp %>% group_by(UF) %>% slice(1)
resp <- resp %>% group_by(VALOR.TELEFONICO.MEDIA) %>% slice(1)
fix(resp)
write.csv(resp, file = "D:/Users/Eduardo/Documents/Curso_R/Questão_6.csv", row.names = FALSE)
write.csv(q6, file = "C:/ProgramData/MySQL/MySQL Server 8.0/Uploads/Q7.csv", row.names = FALSE)
